
GET http://localhost:4000/reports/?reportsId=6090315f77aa5739d0641451
Content-Type: application/json

//POST http://localhost:4000/reports/create
//Content-Type: application/json

//{
//    "userID": "user-2",
//   "marketID": "market-1",
//    "marketName": "Vashi Navi Mumbai",
//    "cmdtyID": "cmdty-1",
//    "marketType": "Mandi",
//    "cmdtyName": "Potato",
//    "priceUnit":"quintal",
//    "convFctr": 100,
//    "price": 1600
//}